name: Static Website CI/CD

on:
  push:
    branches:
      - development
      - non-prod
      - main

jobs:
  development-build-and-deploy:
    if: github.ref == 'ref/heads/development'
    runs-on: ubuntu-latest
    ## environment: development
    steps:
      - name: checkout to code root folder
        uses: actions/checkout@v3
      - name: Cache build dependencies
        uses: actions/cache@v2
        id: cache-node
      - name: Install dependencies
        run: npm i
      - name: Generate Artifacts
        uses: actions/setup-node@v3
        with:
          node-versions: "16.x"
      - name: Build Project
        run: npm run build